### ISSUE TITLE
Endgame forcieren >> Blufor über Zeit stärker werden lassen

### ISSUE THREAD

**Issue by McDiod** [gruppe-adler/TvT_WITA2016.Altis#21]

**Comment by AdlerXiviD** [comment]
1) Eventuell öfter markieren, wenn Opfor schon länger nicht "beschossen" wurde? Wird aber wahrscheinlich schwer mit den Eventhandlern.
2) Grundsätzlich öfter markieren wenn Opfor in Fahrzeug ist? Forcieren, dass Opfor zu Fuss geht
3) Öfter markieren umso länger Agent am Leben?
Wobei die "Sichtung" ist ja eigentlich nicht das Problem. Das Problem ist ja schlichtweg dass der Agent  auf dem Wasser durch Fehlen der FFV-Fahrzeuge nicht antastbar ist und dass der Heli nicht so schnell zu landen ist wie ein Littlebird.
