### ISSUE TITLE
Hinweis bei jeder Agentenmarkierung

### ISSUE THREAD

**Issue by McDiod** [gruppe-adler/TvT_WITA2016.Altis#7]

**Comment by McDiod** [comment]
![gps-bear-grylls-back-track-d-tour-personal-gps-tracking-device-49181311](https://cloud.githubusercontent.com/assets/16549968/25392836/0cba6f14-29da-11e7-9c12-741828782382.jpg)

**Comment by nomisum** [comment]
shall i make a mock of this in PS? 😋

**Comment by McDiod** [comment]
erstmal gucken was @AdlerXiviD will

**Comment by McDiod** [comment]
Ausgelagert nach:
https://github.com/gruppe-adler/grad-gpsTracker
